### ISSUE TITLE
Segmentation Fault on initCoreNLP()

### ISSUE THREAD

**Issue by edugonza** [statsmaths/coreNLP#18]
Hi all,
I have installed coreNLP with:
`devtools::install_github("statsmaths/coreNLP")`

After executing `downloadCoreNLP()`, I loaded the library with `library(coreNLP)`.
The problem appears when initializing the library with `initCoreNLP()`. I get the following error:
`Segmentation fault (core dumped)`

I have the same problem with the coreNLP version in cran-r. It used to work perfectly, until a couple of days a go. I tried with older and newer versions of R without success.

I am running it in Ubuntu Linux 16.04

Any idea of the cause?

**Comment by statsmaths** [comment]
Unfortunately, I have no idea why this would happen. Seg faults are notoriously difficult to debug, particularly remotely with two languages and multiple packages involved. I would suggest, generally and also because of this issue, migrating to my package **cleanNLP**. It is more constantly maintained and may address the issue you have here.
