### ISSUE TITLE
coreNLP NER models to import in R 

### ISSUE THREAD

**Issue by carlosantagiustina** [statsmaths/coreNLP#6]
Hello I have a problem with coreNLP on R, I would like to import specific models for NER and for POS from within R and I don't understand how to do it... does somebody know? thanks

**Comment by statsmaths** [comment]
In order to specify alternative models, you need to construct a properties file. You can use the file included with the package, [StanfordCoreNLP.properties](https://github.com/statsmaths/coreNLP/blob/master/inst/extdata/StanfordCoreNLP.properties), as a starting point. It has commented out examples of doing exactly this.
